### ISSUE TITLE
Error Running CommonError1Test

### ISSUE THREAD

**Issue by philip-alldredge** [cmu-sei/emfta#14]
When running tests, I receive the following error. On first glance it appears to be caused by the generated XML not being exactly the same as expected. Two of the events have a different order.

```
Running org.osate.aadl2.errormodel.emfta.tests.CommonError1Test
SysImpol org.osate.xtext.aadl2.errormodel.errorModel.impl.ErrorModelSubclauseImpl@7aa15a80 (name: EMV2)
[Utils] Probability for Intermediate1:0.0
[Utils] Probability for common_error1_main_commonsource-failstop:0.0
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.787 sec <<< FAILURE! - in org.osate.aadl2.errormodel.emfta.tests.CommonError1Test
commonerrorfta(org.osate.aadl2.errormodel.emfta.tests.CommonError1Test)  Time elapsed: 5.921 sec  <<< FAILURE!
org.junit.ComparisonFailure: error expected:<...e">
  <events name="[a0-failure" description="Error event Failure on component a0"/>
  <events name="s0-ef0-latedelivery" description="Error source ef0 on component s0 from valueout with types {LateDelivery}"/>
  <events name="a1-failure" description="Error event Failure on component a1"/>
  <events type="Intermediate" name="Intermediate1">
    <gate type="AND" events="//@events.0 //@events.2"/>
  </events>
  <events type="Intermediate" name="common_error1_main_commonsource-failstop">
    <gate events="//@events.3 //@events.1]"/>
  </events>
</em...> but was:<...e">
  <events name="[s0-ef0-latedelivery" description="Error source ef0 on component s0 from valueout with types {LateDelivery}"/>
  <events name="a0-failure" description="Error event Failure on component a0"/>
  <events name="a1-failure" description="Error event Failure on component a1"/>
  <events type="Intermediate" name="Intermediate1">
    <gate type="AND" events="//@events.1 //@events.2"/>
  </events>
  <events type="Intermediate" name="common_error1_main_commonsource-failstop">
    <gate events="//@events.3 //@events.0]"/>
  </events>
</em...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.osate.aadl2.errormodel.emfta.tests.CommonError1Test.commonerrorfta(CommonError1Test.java:89)
```

**Comment by lwrage** [comment]
child of #16
