### ISSUE TITLE
NPE during export to EMFTA

### ISSUE THREAD

**Issue by lwrage** [cmu-sei/emfta#4]
This happens using the develop branch when exporting model `TestSystems_TestTriVoter_i_Instance.aaxl2` from project `AADL2AR_Patterns`.
The project is in repo `aadl/models` in directory `aadl2ar` in the lab git.
I suspect that it's caused by the implementation of `{noerror}` handling.

In the export dialog select _state s_err_ and leave _Full tree_ unchecked.

```
java.lang.NullPointerException
	at org.osate.xtext.aadl2.errormodel.util.EM2TypeSetUtil.isNoError(EM2TypeSetUtil.java:699)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseOutgoingErrorPropagation(PropagationGraphBackwardTraversal.java:67)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseIncomingErrorPropagation(PropagationGraphBackwardTraversal.java:474)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:430)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:308)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:308)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:284)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.handleOutgoingErrorPropagationCondition(PropagationGraphBackwardTraversal.java:158)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseOutgoingErrorPropagation(PropagationGraphBackwardTraversal.java:71)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseIncomingErrorPropagation(PropagationGraphBackwardTraversal.java:474)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:430)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseErrorBehaviorState(PropagationGraphBackwardTraversal.java:240)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseCompositeErrorState(PropagationGraphBackwardTraversal.java:512)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:385)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.processCondition(PropagationGraphBackwardTraversal.java:284)
	at org.osate.xtext.aadl2.errormodel.util.PropagationGraphBackwardTraversal.traverseCompositeErrorState(PropagationGraphBackwardTraversal.java:503)
	at org.osate.aadl2.errormodel.emfta.fta.EMFTAGenerator.getEmftaModel(EMFTAGenerator.java:105)
	at org.osate.aadl2.errormodel.emfta.fta.EMFTAGenerator.getEmftaModel(EMFTAGenerator.java:92)
	at org.osate.aadl2.errormodel.emfta.fta.EMFTACreateModel.createModel(EMFTACreateModel.java:96)
	at org.osate.aadl2.errormodel.emfta.actions.EMFTAAction.doAaxlAction(EMFTAAction.java:144)
	at org.osate.ui.actions.AbstractAaxlAction.processAaxlAction(AbstractAaxlAction.java:528)
	at org.osate.ui.actions.AbstractAaxlAction.actionBody(AbstractAaxlAction.java:236)
	at org.osate.ui.actions.AaxlReadOnlyActionAsJob$ActionAsJob.runInWorkspace(AaxlReadOnlyActionAsJob.java:136)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by reteprelief** [comment]
Fixed by a commit to EMV2. The problem was that inNoError did not handle the case when a null type is passed in.
